### PR TITLE
Fix search HTML injection

### PR DESCRIPTION
**Pull request by Tibinsunny**
Hey,
Fix for #15
Changes:
I've added a small function which uses regex to filter out HTML code 

hbr1-fix

Fixed 👏

### CODE REVIEW

**Comment by saifabusaleh** [comment]
Hi @Tibinsunny 

For the other issue fix please create separate pull request, and revert it from here

Thanks

**Comment by saifabusaleh** [comment]
@Tibinsunny  Looks good

One more thing before merge, can you please squash all the commits here into one commit?

You can check online how to do that, if you didn't find I can help you with it

Thanks

**Comment by saifabusaleh** [comment]
@Pustur Yes I can, but it is learning opportunity for him to do it

If he don't want to do it I can do it myself.

**Comment by Tibinsunny** [comment]
squashed all commit. Thanks, I learned something New 😃

> 
> 
> @Tibinsunny Looks good
> 
> One more thing before merge, can you please squash all the commits here into one commit?
> 
> You can check online how to do that, if you didn't find I can help you with it
> 
> Thanks

**Pull request merged**
